parameters:
  - { name: versionOverride, type: string, default: '' }
  - { name: master, type: boolean }
  - { name: connectedServiceName, type: string }

jobs:
  - template: job-base.yml
    parameters:
      displayName: Build
      vmImage: windows-latest

      variables:
        - template: ../variables/extension.yml

        - name: version.override
          value: ${{ parameters.versionOverride }}
          readonly: true

        - ${{ if not(or(parameters.versionOverride, parameters.master)) }}:
          - name: version.patch
            value: $[ counter(variables['system.pullRequest.pullRequestNumber'], 1) ]
            readonly: true

      checkout: self

      steps:
        - template: ../steps/use-tfx-cli.yml

        - task: QueryAzureDevOpsExtensionVersion@2
          displayName: Query extension version
          inputs:
            connectTo: VsTeam
            connectedServiceName: ${{ parameters.connectedServiceName }}
            publisherId: $(extension.publisherId)
            extensionId: $(extension.id)
            ${{ if parameters.master }}:
              versionAction: Minor
            setBuildNumber: true
            extensionVersionOverride: version.override

        - ${{ if not(or(parameters.master, parameters.versionOverride)) }}:
          - pwsh: |
              $version = [version] $Env:BUILD_BUILDNUMBER
              $version = "{0}.{1}" -f $version.ToString(2), $Env:VERSION_PATCH
              "##vso[build.updatebuildnumber]$version"
            displayName: Update build number

        - pwsh: ./build.ps1 -Build -Clear
          displayName: Build tasks

        - task: PackageAzureDevOpsExtension@2
          displayName: Package extension
          name: vsix
          inputs:
            patternManifest: vss-extension.json
            publisherId: $(extension.publisherId)
            extensionId: $(extension.id)
            extensionName: $(extension.name)
            extensionVersion: $(build.buildNumber)
            updateTasksVersion: true
            updateTasksVersionType: minor
            updateTasksId: true

        - publish: $(vsix.extension.outputPath)
          displayName: Publish VSIX artifact
          artifact: VSIX
