parameters:
  - { name: automaticVersion, type: boolean }
  - { name: connectedServiceName, type: string }

jobs:
  - template: job-base.yml
    parameters:
      displayName: Build
      vmImage: windows-latest
      checkout: self

      variables:
        - template: ../variables/extension.yml

      steps:
        - template: ../steps/use-tfx-cli.yml

        - ${{ if parameters.automaticVersion }}:
          - task: QueryAzureDevOpsExtensionVersion@2
            displayName: Query extension version
            inputs:
              connectTo: VsTeam
              connectedServiceName: ${{ parameters.connectedServiceName }}
              publisherId: $(extension.publisherId)
              extensionId: $(extension.id)
              versionAction: Minor
              setBuildNumber: true

        - pwsh: ./build.ps1 -Build -Clear
          displayName: Build tasks

        - task: PackageAzureDevOpsExtension@2
          displayName: Package extension
          name: vsix
          inputs:
            patternManifest: vss-extension.json
            publisherId: $(extension.publisherId)
            extensionId: $(extension.id)
            extensionName: $(extension.name)
            extensionVersion: $(build.buildNumber)
            updateTasksVersion: true
            updateTasksVersionType: minor
            updateTasksId: true

        - publish: $(vsix.extension.outputPath)
          displayName: Publish VSIX artifact
          artifact: VSIX
