parameters:
- {name: automaticVersion, type: boolean}
- {name: connectedServiceName, type: string}
- {name: publisherId, type: string}
- {name: extensionId, type: string}
- {name: extensionName, type: string}
- {name: artifact, type: string}

jobs:
- template: job-base.yml
  parameters:
    displayName: Build
    vmImage: windows-latest

    steps:
    - template: ../steps/use-tfx-cli.yml

    - ${{ if parameters.automaticVersion }}:
      - task: QueryAzureDevOpsExtensionVersion@2
        displayName: Query extension version
        inputs:
          connectTo: VsTeam
          connectedServiceName: ${{ parameters.connectedServiceName }}
          publisherId: ${{ parameters.publisherId }}
          extensionId: ${{ parameters.extensionId }}
          versionAction: Minor
          setBuildNumber: true

    - pwsh: ./build.ps1 -Build -Clear
      displayName: Build tasks

    - task: PackageAzureDevOpsExtension@2
      displayName: Package extension
      name: ${{ parameters.artifact }}
      inputs:
        patternManifest: vss-extension.json
        publisherId: ${{ parameters.publisherId }}
        extensionId: ${{ parameters.extensionId }}
        extensionName: ${{ parameters.extensionName }}
        extensionVersion: $(build.buildNumber)
        updateTasksVersion: true
        updateTasksVersionType: minor
        updateTasksId: true

    - publish: $(${{ parameters.artifact }}.extension.outputPath)
      displayName: Publish ${{ parameters.artifact }} artifact
      artifact: ${{ parameters.artifact }}
