parameters:
- {name: displayName, type: string}
- {name: vmImage, type: string}
- {name: environment, type: string}
- {name: download, type: string, default: none}
- {name: steps, type: stepList}
- {name: timeoutInMinutes, type: number, default: 20}
- {name: cancelTimeoutInMinutes, type: number, default: 5}

jobs:
- deployment:
  displayName: ${{ parameters.displayName }}

  pool:
    vmImage: ${{ parameters.vmImage }}

  timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
  cancelTimeoutInMinutes: ${{ parameters.cancelTimeoutInMinutes }}

  environment: ${{ parameters.environment }}

  strategy:
    runOnce:
      deploy:
        steps:
        - download: ${{ parameters.download }}

        - template: ../steps/display-info.yml

        - ${{ parameters.steps }}
