parameters:
  - { name: name, type: string }
  - { name: displayName, type: string }
  - { name: dependsOn, type: object, default: [] }
  - { name: vmImage, type: string }
  - { name: timeoutInMinutes, type: number, default: 20 }
  - { name: cancelTimeoutInMinutes, type: number, default: 5 }
  - { name: variables, type: object, default: [] }
  - { name: environment, type: string }
  - { name: download, type: string, default: none }
  - { name: steps, type: stepList }

jobs:
  - deployment: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    cancelTimeoutInMinutes: ${{ parameters.cancelTimeoutInMinutes }}

    variables: ${{ parameters.variables }}

    environment: ${{ parameters.environment }}

    strategy:
      runOnce:
        deploy:
          steps:
            - download: ${{ parameters.download }}

            - template: ../steps/list-info.yml

            - ${{ parameters.steps }}
