parameters:
- {name: displayName, type: string}
- {name: vmImage, type: string}
- {name: checkout, type: string, default: self}
- {name: steps, type: stepList}
- {name: timeoutInMinutes, type: number, default: 10}
- {name: cancelTimeoutInMinutes, type: number, default: 10}

jobs:
- job:
  displayName: ${{ parameters.displayName }}

  pool:
    vmImage: ${{ parameters.vmImage }}

  timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
  cancelTimeoutInMinutes: ${{ parameters.cancelTimeoutInMinutes }}

  steps:
  - checkout: ${{ parameters.checkout }}

  - template: ../steps/display-info.yml

  - ${{ parameters.steps }}
