parameters:
  - { name: displayName, type: string }
  - { name: dependsOn, type: object, default: [] }
  - { name: vmImage, type: string }
  - { name: timeoutInMinutes, type: number, default: 20 }
  - { name: cancelTimeoutInMinutes, type: number, default: 5 }
  - { name: strategy, type: object, default: {} }
  - { name: variables, type: object, default: [] }
  - { name: checkout, type: string, default: none }
  - { name: steps, type: stepList }

jobs:
  - job:
    displayName: ${{ parameters.displayName }}
    dependsOn: ${{ parameters.dependsOn }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    cancelTimeoutInMinutes: ${{ parameters.cancelTimeoutInMinutes }}

    strategy: ${{ parameters.strategy }}

    variables: ${{ parameters.variables }}

    steps:
      - checkout: ${{ parameters.checkout }}

      - template: ../steps/list-info.yml
        parameters:
          vmImage: ${{ parameters.vmImage }}

      - ${{ parameters.steps }}
