parameters:
  - { name: displayName, type: string }
  - { name: vmImage, type: string }
  - { name: timeoutInMinutes, type: number, default: 20 }
  - { name: cancelTimeoutInMinutes, type: number, default: 5 }
  - { name: variables, type: object, default: [] }
  - { name: checkout, type: string, default: none }
  - { name: steps, type: stepList }

jobs:
  - job:
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    cancelTimeoutInMinutes: ${{ parameters.cancelTimeoutInMinutes }}

    variables: ${{ parameters.variables }}

    steps:
      - checkout: ${{ parameters.checkout }}

      - template: ../steps/list-info.yml

      - ${{ parameters.steps }}
