parameters:
- {name: connectedServiceName, type: string}
- {name: artifact, type: string}

jobs:
- template: deployment-base.yml
  parameters:
    displayName: Publish
    vmImage: ubuntu-latest
    environment: ${{ parameters.connectedServiceName }}

    steps:
    - template: ../steps/download-artifact.yml
      parameters:
        artifact: ${{ parameters.artifact }}
        path: $(Build.StagingDirectory)/${{ parameters.artifact }}

    - template: ../steps/use-tfx-cli.yml

    - task: PublishAzureDevOpsExtension@2
      displayName: Publish extension
      inputs:
        connectTo: VsTeam
        connectedServiceName: ${{ parameters.connectedServiceName }}
        fileType: vsix
        vsixFile: $(Build.StagingDirectory)/${{ parameters.artifact }}/*.vsix
