parameters:
- {name: gitHubConnection, type: string}
- {name: artifact, type: string}
- {name: extensionName, type: string}

jobs:
- template: deployment-base.yml
  parameters:
    displayName: Release
    vmImage: ubuntu-latest
    environment: ${{ parameters.gitHubConnection }}

    steps:
    - template: ../steps/download-artifact.yml
      parameters:
        artifact: ${{ parameters.artifact }}
        path: $(build.stagingDirectory)/${{ parameters.artifact }}

    - task: GitHubRelease@0
      displayName: Release extension
      inputs:
        gitHubConnection: ${{ parameters.gitHubConnection }}
        tagSource: manual
        tag: v$(build.buildNumber)
        title: ${{ parameters.extensionName }} v$(build.buildNumber)
        assets: $(build.stagingDirectory)/${{ parameters.artifact }}/*
