parameters:
  - { name: gitHubConnection, type: string }

jobs:
  - template: deployment-base.yml
    parameters:
      name: Release
      displayName: Release
      vmImage: ubuntu-latest

      variables:
        - template: ../variables/extension.yml

      environment: ${{ parameters.gitHubConnection }}

      steps:
        - template: ../steps/download-artifact.yml
          parameters:
            artifact: VSIX
            path: $(build.stagingDirectory)/VSIX

        - task: GitHubRelease@0
          displayName: Release extension
          inputs:
            gitHubConnection: ${{ parameters.gitHubConnection }}
            tagSource: manual
            tag: v$(build.buildNumber)
            title: $(extension.name) v$(build.buildNumber)
            assets: $(build.stagingDirectory)/VSIX/*
