parameters:
  - { name: displayName, type: string }
  - { name: debug, type: boolean, default: false }

jobs:
  - template: job-base.yml
    parameters:
      displayName: ${{ parameters.displayName }}
      vmImage: windows-latest

      variables:
        system.debug: ${{ parameters.debug }}

      steps:
        - task: ListFiles@1
          displayName: List files
          condition: always()
          inputs:
            rootDir: $(Agent.WorkFolder)

        - task: RetainRun@1
          displayName: Retain run
          condition: always()
