parameters:
  - { name: displayName, type: string }
  - { name: debug, type: boolean, default: false }

jobs:
  - template: job-base.yml
    parameters:
      displayName: ${{ parameters.displayName }}
      vmImage: windows-latest

      variables:
        system.debug: ${{ parameters.debug }}

      steps:
        - task: ListFiles@1
          displayName: List files
          condition: always()

        - task: Comment@1
          displayName: Comment
          condition: always()
          inputs:
            comments: |
              Here are some ...
              ... awesome comments!
            includeCommentsInLog: true

        - task: RetainRun@1
          displayName: Retain run
          condition: always()
