parameters:
  - { name: dependsOn, type: object }

jobs:
  - template: job-base.yml
    parameters:
      displayName: Run System tests
      dependsOn: ${{ parameters.dependsOn }}
      vmImage: windows-latest

      strategy:
        maxParallel: 1
        matrix:
          Debug:
            debug: true
          Normal:
            debug: false

      variables:
        - name: system.debug
          value: $(debug)
          readonly: true

      steps:
        # ListApps, ListSystemInfo and ListVariables tasks are already called in job-base.yml

        - task: ListFiles@1
          displayName: List files
          condition: always()
          inputs:
            rootDir: $(Agent.WorkFolder)

        - task: RetainRun@1
          displayName: Retain run
          condition: always()
