parameters:
  - { name: displayName, type: string }

jobs:
  - template: job-base.yml
    parameters:
      displayName: System Tests
      vmImage: windows-latest

      strategy:
        maxParallel: 1
        matrix:
          Debug:
            system.debug: true
          Normal:
            system.debug: false

      steps:
        - task: ListFiles@1
          displayName: List files
          condition: always()
          inputs:
            rootDir: $(Agent.WorkFolder)

        - task: RetainRun@1
          displayName: Retain run
          condition: always()
