parameters:
- {name: displayName, type: string}
- {name: vmImage, type: string}
- {name: publishCodeCoverage, type: boolean, default: false}

jobs:
- template: job-base.yml
  parameters:
    displayName: Test
    vmImage: ${{ parameters.vmImage }}

    steps:
    - pwsh: ./build.ps1 -Build
      displayName: Build tasks

    - pwsh: ./build.ps1 -${{ parameters.displayName }}Tests -CodeCoverage
      displayName: Run tests

    - task: PublishTestResults@2
      displayName: Publish test results
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: TestResults-${{ parameters.displayName }}Tests.xml
        testRunTitle: ${{ parameters.displayName }} Tests
      condition: succeededOrFailed()

    - task: reportgenerator@4
      displayName: Generate code coverage report
      inputs:
        reports: Coverage-${{ parameters.displayName }}Tests.xml
        targetdir: CoverageReport
        reporttypes: HtmlInline_AzurePipelines_Dark;Badges
        sourcedirs: $(Pipeline.Workspace)
        tag: ''

    - ${{ parameters.publishCodeCoverage }}:
      - task: PublishCodeCoverageResults@1
        displayName: Publish code coverage
        inputs:
          codeCoverageTool: JaCoCo
          summaryFileLocation: $(System.DefaultWorkingDirectory)/Coverage-${{ parameters.displayName }}Tests.xml
          reportDirectory: $(System.DefaultWorkingDirectory)/CoverageReport

    - publish: CoverageReport
      displayName: Publish code coverage report artifact
      artifact: ${{ parameters.displayName }} Tests
