parameters:
- {name: displayName, type: string}
- {name: publishCodeCoverage, type: boolean, default: false}

jobs:
- template: job-base.yml
  parameters:
    displayName: Test
    vmImage: windows-latest

    steps:
    - pwsh: ./build.ps1 -Build
      displayName: Build tasks

    - powershell: ./build.ps1 -${{ parameters.displayName }}Tests
      displayName: Run tests (PowerShell)

    - pwsh: ./build.ps1 -${{ parameters.displayName }}Tests -CodeCoverage
      displayName: Run tests (PowerShell Core)

    - task: PublishTestResults@2
      displayName: Publish test results
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: TestResults-${{ parameters.displayName }}Tests.xml
        testRunTitle: ${{ parameters.displayName }} Tests

    - task: reportgenerator@4
      displayName: Generate code coverage report
      inputs:
        reports: Coverage-${{ parameters.displayName }}Tests.xml
        targetdir: CoverageReport
        reporttypes: HtmlInline_AzurePipelines_Dark;Badges
        sourcedirs: $(pipeline.workspace)
        tag: ''

    - ${{ if parameters.publishCodeCoverage }}:
      - task: PublishCodeCoverageResults@1
        displayName: Publish code coverage
        inputs:
          codeCoverageTool: JaCoCo
          summaryFileLocation: $(system.defaultWorkingDirectory)/Coverage-${{ parameters.displayName }}Tests.xml
          reportDirectory: $(system.defaultWorkingDirectory)/CoverageReport

    - publish: CoverageReport
      displayName: Publish code coverage report artifact
      artifact: ${{ parameters.displayName }} Tests
