parameters:
  - { name: dependsOn, type: object }

jobs:
  - template: job-base.yml
    parameters:
      displayName: Wait for Update
      dependsOn: ${{ parameters.dependsOn }}
      vmImage: ubuntu-latest

      variables:
        - template: ../variables/extension.yml

      steps:
        - template: ../steps/wait-extension.yml
