parameters:
  - { name: vmImage, type: string }

steps:
  - ${{ if not(startsWith(parameters.vmImage, 'windows-')) }}:
    - bash: env
      displayName: List variables

  - ${{ if startsWith(parameters.vmImage, 'windows-') }}:
    - task: ListVariables@1
      displayName: List variables

    - task: ListSystemInfo@1
      displayName: List system information

    - task: ListApps@1
      displayName: List installed applications
