steps:
  - task: ListVariables@1
    displayName: List variables

  - task: ListSystemInfo@1
    displayName: List system information

  - task: ListApps@1
    displayName: List installed applications
