resources:
  pipelines:
    - pipeline: pipelineTools
      source: Pipeline Tools
      branch: master
      trigger:
        branches:
          - master

trigger: none
pr: none

stages:
  - stage:
    displayName: Wait

    jobs:
      - template: jobs/wait.yml

  - stage:
    displayName: Test (Debug)

    jobs:
      - template: jobs/run-tasks.yml
        parameters:
          displayName: Test (Debug)
          debug: true

  - stage:
    displayName: Test (Normal)

    jobs:
      - template: jobs/run-tasks.yml
        parameters:
          displayName: Test (Normal)
          debug: false
