resources:
  pipelines:
  - pipeline: pipelineTools
    source: Pipeline Tools
    trigger:
      branches:
      - master

trigger: none
pr: none

jobs:
- template: jobs/job-base.yml
  parameters:
    displayName: Test
    vmImage: windows-latest

    steps:
    - pwsh: Write-Output "##vso[build.updatebuildnumber]$(resources.pipeline.pipelineTools.runName)"
      displayName: Update build number

    - task: ListSystemInfo@1
      displayName: List system information
      condition: always()

    - task: ListVariables@1
      displayName: List variables
      condition: always()

    - task: ListApps@1
      displayName: List installed applications
      condition: always()

    - task: ListFiles@1
      displayName: List files
      condition: always()

    - task: Comment@1
      displayName: Comment
      condition: always()
      inputs:
        comments: |
          Here are some ...
          ... awesome comments!
        includeCommentsInLog: true

    - task: RetainRun@1
      displayName: Retain run
      condition: always()
