resources:
  pipelines:
  - pipeline: pipelineTools
    source: Pipeline Tools
    trigger:
      branches:
      - master

trigger: none
pr: none

stages:
- stage:
  displayName: Wait

  jobs:
  - template: jobs/job-base.yml
    parameters:
      displayName: Wait
      vmImage: ubuntu-latest
      checkout: none

      steps:
      - bash: echo '##vso[build.updatebuildnumber]$(resources.pipeline.pipelineTools.runName)'
        displayName: Update build number

      - bash: sleep 300
        displayName: Wait for the extension to update

- stage:
  displayName: Test

  jobs:
  - template: jobs/job-base.yml
    parameters:
      displayName: Test
      vmImage: windows-latest
      checkout: none

      steps:
      - task: ListSystemInfo@1
        displayName: List system information
        condition: always()

      - task: ListVariables@1
        displayName: List variables
        condition: always()

      - task: ListApps@1
        displayName: List installed applications
        condition: always()

      - task: ListFiles@1
        displayName: List files
        condition: always()

      - task: Comment@1
        displayName: Comment
        condition: always()
        inputs:
          comments: |
            Here are some ...
            ... awesome comments!
          includeCommentsInLog: true

      - task: RetainRun@1
        displayName: Retain run
        condition: always()
