parameters:
  - name: version
    displayName: Version
    type: string
    default: Automatic

trigger:
  - master
pr:
  - master

variables:
  - name: connectedServiceName
    value: Visual Studio Marketplace
    readonly: true

  - name: gitHubConnection
    value: GitHub Releases
    readonly: true

stages:
  - stage: build
    displayName: Build
    dependsOn: []

    jobs:
      - template: jobs/build.yml
        parameters:
          ${{ if ne(parameters.version, 'Automatic') }}:
            versionOverride: ${{ parameters.version }}
          master: ${{ eq(variables['build.sourceBranch'], 'refs/heads/master') }}
          connectedServiceName: $(connectedServiceName)

  - stage: unitTests
    displayName: Unit Tests
    dependsOn: []

    jobs:
      - template: jobs/test.yml
        parameters:
          test: Unit
          publishCodeCoverage: true

  - stage: integrationTests
    displayName: Integration Tests
    dependsOn: []

    jobs:
      - template: jobs/test.yml
        parameters:
          test: Integration

  - ${{ if eq(variables['build.sourceBranch'], 'refs/heads/master') }}:
    - stage:
      displayName: Deploy
      dependsOn:
        - build
        - unitTests
        - integrationTests

      jobs:
        - template: jobs/publish.yml
          parameters:
            connectedServiceName: $(connectedServiceName)

        - template: jobs/release.yml
          parameters:
            gitHubConnection: $(gitHubConnection)

    - stage:
      displayName: Wait for Update

      jobs:
        - template: jobs/wait.yml

    - stage:
      displayName: Test (Debug)

      jobs:
        - template: jobs/run-tasks.yml
          parameters:
            displayName: Test (Debug)
            debug: true

    - stage:
      displayName: Test (Normal)

      jobs:
        - template: jobs/run-tasks.yml
          parameters:
            displayName: Test (Normal)
            debug: false
